language: go
sudo: false

matrix:
  include:
    - go: "1.10.x"
    - go: "1.11.x"
    - go: "1.12.x"
    - go: tip
  allow_failures:
    - go: tip

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

script:
  - make lint
  - make test
